apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kfo58guzy-go-gitops
  description: This is GitOps manifest for kfo58guzy-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=kfo58guzy-go
    backstage.io/kubernetes-id: kfo58guzy-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kfo58guzy-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kfo58guzy-go
